### ISSUE TITLE
Verify that new scripts are added to json files

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlsfuzzer#156]
When a new test script is added it is easy to forget to add it to json files that configure the libraries (`tests/tlslite-ng.json`, `tlslite-ng-random-subset.json`, possibly others).

Add script that runs in Travis that will verify that all scripts in `scripts/`are mentioned at least once in every json file.

**Comment by nmav** [comment]
It may be implied, but to make it explicit, it would be very nice for such a script to be callable not only in travis, but by any 3rd party with a json file. Ideally it should also accept a list of tests that are intentionally not included (e.g., due to running time).

**Comment by tomato42** [comment]
@nmav tests that run for long time (more than 10s on my laptop) all support `-n` option to limit the number of tests that are run. Because of the way python works, it's a random subset of tests that are defined in any script. See `tlslite-ng-random-subset` for example of usage.

**Comment by gekios** [comment]
Hello everyone,
I am working on this issue too and I have made some progress. I haven't communicated it properly though and I saw that it was assigned today. 
@NoName115 Robert please let me know if you have already started working on it, or completed it already, so I won't keep working on this too. Thank you.

**Comment by tomato42** [comment]
@gekios Hi,
I don't think Robert spent on this more than 2h today, so probably not yet finished.
Where can we find your code? When you'll be able to propose a PR with it? Would you be ok with Robert basing the work off of your code (if you are not able to finish it soon), or would you prefer to finish it yourself?

**Comment by gekios** [comment]
@tomato42 Hello Hubert,
Actually I am almost done with the script, apart from some details that I am not sure. I am just currently working on it on a test repo. I can send a PR even today or tomorrow worst case scenario, I just don't want to be unfair to Robert, since he assigned the issue which is according to normal process, while I didn't communicate that I was working on it.

**Comment by NoName115** [comment]
@gekios Hi,
You can work on this issue, that's no problem for me. But please for the future, add comment to issue that you are working on, so we are not doing the same stuff twice, thank you.

And some info from our discussion with hubert, about this issue:
* don't hardcore tlslite-ng and tlslite-ng-random json file names in script
* and add this script to Makefile, to "test" target

**Comment by tomato42** [comment]
@gekios reviewed that patch, please fix those issues and propose a PR

**Comment by gekios** [comment]
@NoName115 Hello Robert,
I am really sorry for any time you wasted on this because of my mistake. The issue was open for long so I mistakenly thought that it would be fine just to do it and post it after I am done. I try not to make the same mistake in the future. 

@tomato42 I apologize for the delay Hubert but I was really busy at work today and I didn't manage to find some time during the day. I have fixed the issues you pointed out. Please check and let me know if I have missed anything. Thank you
