### ISSUE TITLE
test-large-hello.py: invalid client hello fragmentation

### ISSUE THREAD

**Issue by nmav** [tomato42/tlsfuzzer#160]
Going through the client hello fragmentation tests of test-large-hello.py, I believe they are incorrect. Checking through wireshark, I see the first record packet carrying 1 or 2 bytes, which not sufficient even for the handshake header size. I do not think that this fragmentation is interesting in practice. There is no reason for an implementation to fragment below the handshake header size (which gnutls doesn't tolerate).

Related to: https://gitlab.com/gnutls/gnutls/issues/272

I believe the same issue existing in:
test-record-layer-fragmentation.py  at "small, maximum fragmentation: 1 fragment - 20B extension", "medium, maximum fragmentation: 1 fragment - 1024B extension", "non fragmented, over fragmentation limit: 65535 fragment - 16332B extension".

**Comment by tomato42** [comment]
both of those tests do exactly what they are supposed to do - the `test-large-hello.py` is checking (among other things) if the big client hello messages will be accepted by server, even if the fragmentation happens in the handshake protocol header

similar idea was used for the `test-record-layer-fragmentation.py` to see if the server will accept even excessively fragmented messages

since RFC specifies that the minimal length of Alert and Handshake message records is 1 byte, those are all valid messages and they should be accepted.
