### ISSUE TITLE
Fuzz mac in AEAD ciphers (GCM/CHACHA20-POLY1305)

### ISSUE THREAD

**Issue by silverfoxy** [tomato42/tlsfuzzer#93]
fuzz_mac() is not working with AEAD ciphers, what happens is that the server sends application data and everything works fine. To test it, swap "ciphers = [CipherSuite.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256]" in test-fuzzed-mac.py script.
Any hints how to make this work?

**Comment by tomato42** [comment]
fuzz_mac() currently knows how to fuzz only MAC-then-Encrypt ciphers, ones in which the MAC value is not sent as plaintext.

Since the authentication tag in AES-GCM ciphers is sent unencrypted, you can use fuzz_encrypted_message() for fuzzing it, see [scripts/test-fuzzed-ciphertext.py](https://github.com/tomato42/tlsfuzzer/blob/master/scripts/test-fuzzed-ciphertext.py)
